// Initial leads data from Bangalore Security Dialogue spreadsheet
const INITIAL_LEADS = [
  {
    "id": 1,
    "organisation": "Deloitte",
    "stakeholder": "Sudeepta Veerapaneni",
    "designation": "Partner & Chief Innovation Officer",
    "email": "sveerapaneni@deloitte.com",
    "phone": "",
    "location": "Hyderabad",
    "industry": "Consulting",
    "mainBusiness": "Consulting Practice",
    "linkedin": "https://www.linkedin.com/in/romal-shetty-4590361?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BqpVOlgpdTaiv96yKS8GKKg%3D%3D",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 2,
    "organisation": "Castrol India",
    "stakeholder": "Kedar Lele & Jaya Jamrani",
    "designation": "MD, India & VP, Global Marketing",
    "email": "GMEMarketingRequests@castrol.com",
    "phone": "96745 20520",
    "location": "Mumbai",
    "industry": "Petrochemicals",
    "mainBusiness": "Metalworking Fluids",
    "linkedin": "https://www.linkedin.com/in/kedarlele?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3B4kplxWTGTLm%2BUQN479UGDg%3D%3D",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 3,
    "organisation": "Horizon Industrial Parks",
    "stakeholder": "Ronnie Zaiwalla",
    "designation": "Senior Marketing Manager",
    "email": "ronnie.zaiwalla@hiparks.com",
    "phone": "9930598639",
    "location": "Mumbai",
    "industry": "Industrial Parks",
    "mainBusiness": "Commercial Properties",
    "linkedin": "https://www.linkedin.com/in/ronniezaiwalla?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BQY0ACvZlSZyr2%2FlQ1oCimQ%3D%3D",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 4,
    "organisation": "Cumi Murugappa",
    "stakeholder": "Sridharan Rangarajan",
    "designation": "Managing Director",
    "email": "sridharanr@cumi.murugappa.com, cumigeneral@cumi.murugappa.com, email@cumi.murugappa.com, rekhas@cumi.murugappa.com",
    "phone": "",
    "location": "Chennai",
    "industry": "Industrial Tools",
    "mainBusiness": "Precision Tools & Manufacturing",
    "linkedin": "N.A",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 5,
    "organisation": "SCOPE (Standing Conference of Public Enterprises)",
    "stakeholder": "Atul Sobti",
    "designation": "Director General",
    "email": "scopedg@scopeonline.in, samridhi@scopeonline.in",
    "phone": "95120-2511826",
    "location": "New Delhi",
    "industry": "Defence & Aerospace",
    "mainBusiness": "Industry Body",
    "linkedin": "https://www.linkedin.com/in/atul-sobti-a70a281ab?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BigL26Q3YQYqzKzsvEnW80A%3D%3D",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 6,
    "organisation": "Safran India",
    "stakeholder": "Jetendra Gavankar",
    "designation": "CEO & Country Head",
    "email": "jetendra.gavankar@safran-group.com",
    "phone": "",
    "location": "New Delhi",
    "industry": "Defence & Aerospace",
    "mainBusiness": "Component Manufacturing",
    "linkedin": "https://www.linkedin.com/in/jsgavankar?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3B35UwHuBHQ7%2Bm7A%2FaQglh6w%3D%3D",
    "pointOfContact": "Ajay",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 7,
    "organisation": "Pratt & Whitney India",
    "stakeholder": "Ashish Saraf",
    "designation": "Vice President & Country Head",
    "email": "Ashish.Saraf@prattwhitney.com ",
    "phone": "",
    "location": "New Delhi",
    "industry": "Defence & Aerospace",
    "mainBusiness": "Component Manufacturing",
    "linkedin": "https://www.linkedin.com/in/ashish-saraf-bb39a75?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BuJ%2FYGJ5IQMONamyzY%2FAOjQ%3D%3D",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 8,
    "organisation": "Zoho Corporation",
    "stakeholder": "Hariharan Muralimanohar",
    "designation": "Head of Marketing (Zoho One), Zoho Meeting",
    "email": "hariharan.murali@zohocorp.com, muthumeena@zohocorp.com",
    "phone": "99529 28383",
    "location": "Chennai",
    "industry": "Enterprise Software",
    "mainBusiness": "Cloud Software, SaaS",
    "linkedin": "https://www.linkedin.com/in/muthumeena-sudalaimuthu?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BMBlwUuUGSjuvf2az1PVZnA%3D%3D",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 9,
    "organisation": "Asian Paints",
    "stakeholder": "Amit Syngle",
    "designation": "MD & CEO",
    "email": "",
    "phone": "",
    "location": "Mumbai",
    "industry": "Paints",
    "mainBusiness": "Paints & Coating",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 10,
    "organisation": "Forbes Precision Tools (Totem)",
    "stakeholder": "Mahesh Tahilyani",
    "designation": "Managing Director",
    "email": "mahesh.tahilyani@forbesprecision.co.in",
    "phone": "",
    "location": "Mumbai",
    "industry": "Industrial Tools",
    "mainBusiness": "Precision Tools & Manufacturing",
    "linkedin": "",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 11,
    "organisation": "Equirus",
    "stakeholder": "Ajay Garg",
    "designation": "MD",
    "email": "ajay@equirus.com",
    "phone": "",
    "location": "Mumbai",
    "industry": "Financial Services",
    "mainBusiness": "Investment Banking & Advisory",
    "linkedin": "https://www.linkedin.com/in/ajay-garg-95889?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BAQgSyX5ZQjuGf4SsEYgifQ%3D%3D",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 12,
    "organisation": "CommerceCX",
    "stakeholder": "Vasanth Mosoor",
    "designation": "MD",
    "email": "vasanth@commercecx.com",
    "phone": "",
    "location": "Hyderabad",
    "industry": "Enterprise Software",
    "mainBusiness": "IT Services & Consulting",
    "linkedin": "https://www.linkedin.com/in/vasanth-mosoor?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3Btr6tNr5ITQmfUQcHyQvlhQ%3D%3D",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 13,
    "organisation": "TopSolid India",
    "stakeholder": "Sunil Desai",
    "designation": "Founder & Director",
    "email": "sunil@designcell.org",
    "phone": "8830094873",
    "location": "Mumbai",
    "industry": "Industrial Tools",
    "mainBusiness": "Industrial Machinery Manufacturing",
    "linkedin": "https://www.linkedin.com/in/sunil-desai-3876ba21?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BHFXe67tLS720%2FB2PrMHllw%3D%3D",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 14,
    "organisation": "Marposs India",
    "stakeholder": "Luca Matteucci",
    "designation": "Managing Director",
    "email": "luca.matteucci@in.marposs.com",
    "phone": "9958644111",
    "location": "New Delhi",
    "industry": "Industrial Tools",
    "mainBusiness": "Measurement & Control of Precision Equipment",
    "linkedin": "https://www.linkedin.com/in/lucamatteucci83?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3B3iAUObFgS4idJoMDGI9t6A%3D%3D",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 15,
    "organisation": "Oemeta India Pvt Ltd",
    "stakeholder": "Abhimanyu Barthwal",
    "designation": "Director",
    "email": "barthwal@oemeta.com",
    "phone": "",
    "location": "Pune",
    "industry": "Chemical Manufacturing",
    "mainBusiness": "Metalworking Fluids",
    "linkedin": "https://www.linkedin.com/in/abhimanyu-barthwal-32492937?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BT8jWoArSTLq4NXKSXp6a4g%3D%3D",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 16,
    "organisation": "Blue Photon Technology India Pvt Ltd",
    "stakeholder": "Akhil Mittal",
    "designation": "CEO",
    "email": "akhil@bluephotongrip.in, erakhilmittal@gmail.com",
    "phone": "9034116342, 93969 44045",
    "location": "Ambala",
    "industry": "Industrial Tools",
    "mainBusiness": "Industrial Machinery Manufacturing",
    "linkedin": "https://www.linkedin.com/in/mittalakhil87?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BUbUWSaB%2BQmWZCF6blB0gSQ%3D%3D",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 17,
    "organisation": "Zebra Technologies",
    "stakeholder": "Robert Armstrong & Ajay Rao",
    "designation": "CMO and Head - Govt & Enterprise Business",
    "email": "robert.j.armstrong@zebra.com, arao2@zebra.com, arao@zebra.com",
    "phone": "99990 20124, 98210 83635",
    "location": "Thane",
    "industry": "Enterprise Software",
    "mainBusiness": "IT Services & Consulting, Surveillance Tools",
    "linkedin": "https://www.linkedin.com/in/rjarmstrongjr?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BliK5Vvf4Q8CB7M6zJLIqBA%3D%3D, https://www.linkedin.com/in/ajayrao11477?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BrA%2Fp%2FyTPQbagMiEC4h5aKw%3D%3D",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 18,
    "organisation": "Creative EDM Engineering",
    "stakeholder": "Deepak Kumar Gupta",
    "designation": "Director",
    "email": "deepak.gupta@kodixodel.com, edmtools@gmail.com",
    "phone": "9313066574, 70241 564561",
    "location": "New Delhi",
    "industry": "Industrial Tools",
    "mainBusiness": "Precision Tools & Manufacturing",
    "linkedin": "https://www.linkedin.com/in/deepak-gupta-7537589?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BZX%2BZWtl%2FSPmKzafank8qCg%3D%3D",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 19,
    "organisation": "Micro Engineers India",
    "stakeholder": "Mukhwinder Singh Bhurjee",
    "designation": "Director",
    "email": "",
    "phone": "9820057877",
    "location": "Mumbai",
    "industry": "Industrial Tools",
    "mainBusiness": "Corrugated Box Making Machine & Flexo Printing Machine",
    "linkedin": "https://www.microengineersindia.com/about-us.html",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 20,
    "organisation": "Brigade Group",
    "stakeholder": "Pavitra Shankar",
    "designation": "MD",
    "email": "pavitra@brigadegroup.com, pavitrashankar@gmail.com, sunilk@brigadegroup.com",
    "phone": "97400 13037",
    "location": "Bangalore",
    "industry": "Real Estate Developer",
    "mainBusiness": "Residential & Commercial Spaces",
    "linkedin": "https://www.linkedin.com/in/pavitrashankar?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BzTy%2BAR%2BZQP297WVjL1cgIg%3D%3D",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 21,
    "organisation": "Data Patterns (India) Ltd",
    "stakeholder": "Vijay Ananth K",
    "designation": "COO",
    "email": "vijay@datapatterns.co.in, manvi.bhasin@datapatterns.co.in, venkat@datapatterns.co.in, companysecretary@datapatterns.co.in",
    "phone": "",
    "location": "Chennai",
    "industry": "Defence & Aerospace",
    "mainBusiness": "Electronics",
    "linkedin": "https://www.datapatternsindia.com/aboutus/directors.php#:~:text=Srinivasagopalan%20Rangarajan%2C%20is%20the%20Chairman,corporate%20affairs%2C%20finance%20and%20marketing.",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 22,
    "organisation": "MSA Global Technology & Engineering Pvt. Ltd",
    "stakeholder": "Angad Singh Atwal & JS Goraya, Executive Vice President",
    "designation": "Founder & Promoter",
    "email": "angad.atwal@msa-global.com",
    "phone": "9923080722",
    "location": "New Delhi",
    "industry": "Defence & Aerospace",
    "mainBusiness": "Component Manufacturing",
    "linkedin": "https://www.linkedin.com/in/angad-singh-atwal-b14010265?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3Bi8Vk%2F%2FokSWqmbQchbpkwyg%3D%3D",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 23,
    "organisation": "Aerospace India Association",
    "stakeholder": "Dr. Srinivasan Dwarakanath",
    "designation": "DG",
    "email": "kusuma@aia.org.in, dwarakanath2050@gmail.com",
    "phone": "",
    "location": "Bangalore",
    "industry": "Defence & Aerospace",
    "mainBusiness": "Industry Body",
    "linkedin": "https://www.aia.org.in/blank-6, https://www.linkedin.com/in/sdwaraka?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BJ2aASRaRSJyJmxi1yU7HzA%3D%3D",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 24,
    "organisation": "Tool and Gauge Manufacturers Association of India [TAGMA India]",
    "stakeholder": "Devaraya Manjunath Sheregar",
    "designation": "President",
    "email": "sheregar@devutools.com, president@tagmaindia.org",
    "phone": "",
    "location": "Mumbai",
    "industry": "Industrial Tools",
    "mainBusiness": "Industry Body",
    "linkedin": "https://www.linkedin.com/in/devaraya-m-sheregar-4b234b167?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3B3ez8ExXzSPektnvxrlPPCw%3D%3D",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 25,
    "organisation": "Collins Aerospace",
    "stakeholder": "Savyasachi Srinivas",
    "designation": "Vice President",
    "email": "savyasachi.srinivas@collins.com",
    "phone": "9866611411",
    "location": "Bangalore",
    "industry": "Defence & Aerospace",
    "mainBusiness": "Component Manufacturing",
    "linkedin": "https://www.linkedin.com/in/savyasachi-srinivas-3b7b3a18?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3B4I3I0dzKT6eR1t%2BhRNSdgg%3D%3D",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 26,
    "organisation": "CAPA India",
    "stakeholder": "Kapil Kaul",
    "designation": "CEO & Director",
    "email": "kk@capaindia.com",
    "phone": "98116 32498",
    "location": "New Delhi",
    "industry": "Defence & Aerospace",
    "mainBusiness": "Consulting & Research",
    "linkedin": "https://www.linkedin.com/in/kapil-kaul-846a614?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3Bp3%2Bkcj%2BEQkmCq%2FEJkJ%2BG3w%3D%3D",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 27,
    "organisation": "Air India Aviation Training Academy",
    "stakeholder": "Sunil Bhaskaran",
    "designation": "Director",
    "email": "sunil.bhaskaran@airindia.in",
    "phone": "",
    "location": "Gurugram",
    "industry": "Defence & Aerospace",
    "mainBusiness": "Training",
    "linkedin": "https://www.linkedin.com/in/sunil-bhaskaran-31ab3b14/",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 28,
    "organisation": "Sansera Engineering Pvt. Ltd",
    "stakeholder": "F R Singhvi",
    "designation": "Joint Managing Director",
    "email": "fr@sansera.in",
    "phone": "080 \u2013 27839081",
    "location": "New Delhi",
    "industry": "Industrial Tools",
    "mainBusiness": "Industrial Machinery Manufacturing",
    "linkedin": "https://www.linkedin.com/in/f-r-singhvi-885621a5?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BsJ6X47rORryPlZWGgyadvg%3D%3D",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 29,
    "organisation": "JJG Aero",
    "stakeholder": "Anuj Jhunjhunwala",
    "designation": "CEO",
    "email": "anuj.jhunjhunwala@bdjgroup.com",
    "phone": "9903318000",
    "location": "Bangalore",
    "industry": "Defence & Aerospace",
    "mainBusiness": "Component Manufacturing",
    "linkedin": "https://www.linkedin.com/in/anuj-jhunjhunwala-76044a?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BanKQH5yQT3O2slQKBRbnhA%3D%3D",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 30,
    "organisation": "Cyient",
    "stakeholder": "Kushal Jadia",
    "designation": "Senior VP & CTO",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 31,
    "organisation": "Delopt",
    "stakeholder": "Suresh Baroth",
    "designation": "CEO",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 32,
    "organisation": "Hical Technologies Pvt Ltd",
    "stakeholder": "Sujaya Sashikiran",
    "designation": "Managing Director",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 33,
    "organisation": "Aequs Pvt Ltd",
    "stakeholder": "Rajeev Kaul",
    "designation": "MD & CEO",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 34,
    "organisation": "Mckinsey & Company",
    "stakeholder": "Amber Dubey",
    "designation": "Senior Advisor & former JS (Civil Aviation)",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 35,
    "organisation": "The ePlane Co.",
    "stakeholder": "Satya Chakravarthy",
    "designation": "Founder",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 36,
    "organisation": "Rattan India Enterprises Ltd",
    "stakeholder": "Sarath Chandra Gudlavallet",
    "designation": "CEO - NeoSky Drones",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 37,
    "organisation": "Airbus",
    "stakeholder": "Suraj Chettri",
    "designation": "VP, Head of HR - India & South Asia",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 38,
    "organisation": "GE Aviation",
    "stakeholder": "Uma Maheshwar",
    "designation": "CTO",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 39,
    "organisation": "Fortinet",
    "stakeholder": "Vishak Raman",
    "designation": "Head, India & SAARC Business",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 40,
    "organisation": "SpiceJet",
    "stakeholder": "Ajay Singh",
    "designation": "Chairman & MD",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 41,
    "organisation": "Air India Express",
    "stakeholder": "Aloke Singh",
    "designation": "MD",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "https://www.linkedin.com/in/alokesingh64?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BD0F2IxbwTmidAGHKdIJcdg%3D%3D",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 42,
    "organisation": "Asteria Aerospace",
    "stakeholder": "Nihar Vartak",
    "designation": "Co-founder",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 43,
    "organisation": "Unimech Aerospace",
    "stakeholder": "Anil Kumar P.",
    "designation": "Chairman & MD",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 44,
    "organisation": "CAE India Pvt Ltd",
    "stakeholder": "Vikas Khurma",
    "designation": "Director",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "https://www.linkedin.com/in/vikas-khurma-7b84343?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BQr0fVuPhQUusqU8%2BEUOuiQ%3D%3D",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 45,
    "organisation": "Bell India Operations",
    "stakeholder": "Shriram Ghatpande",
    "designation": "Director, Business Development",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 46,
    "organisation": "Moog Inc",
    "stakeholder": "Shyam Karigiri",
    "designation": "Managing Director",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "https://www.linkedin.com/in/shyam-karigiri-960a632?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BlBdfp8L4QJaRY2aBkNO1BQ%3D%3D",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 47,
    "organisation": "Rolls-Royce Aerospace",
    "stakeholder": "Seenivasan Balasubramanian",
    "designation": "CEO",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "https://www.linkedin.com/in/seenivasan-balasubramanian-a97b041a?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3Btg1eQMJ%2FQoqFIENfKRs8nA%3D%3D",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 48,
    "organisation": "Maini Precision",
    "stakeholder": "Gautam Maini",
    "designation": "Managing Director",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "https://www.linkedin.com/in/gautam-maini-5110866?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BG7A%2FAAoaQqSZ1oXAJo1zAQ%3D%3D",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 49,
    "organisation": "Astrogate Labs",
    "stakeholder": "Nitish Singh",
    "designation": "Founder & CEO",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "https://www.linkedin.com/in/singh-nitish-kr?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BEZsvlv0XSwSNq6Jwz4gBXA%3D%3D",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 50,
    "organisation": "Ignis Aerospace & Design Pvt Ltd",
    "stakeholder": "Prahalad Rai Agiwal",
    "designation": "Director",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 51,
    "organisation": "BEL-Thales Systems Ltd",
    "stakeholder": "G Ravi",
    "designation": "Vice CEO",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "https://www.thalesgroup.com/en/india/meet-our-people-india/g-ravi",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 52,
    "organisation": "Hindustan Aeronautics Ltd",
    "stakeholder": "Dr. D.K Sunil",
    "designation": "Chairman & MD",
    "email": "marketing@hal-india.co.in",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 53,
    "organisation": "Centum Electronics",
    "stakeholder": "Apparao V Mallavarapu",
    "designation": "Chairman & MD",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 54,
    "organisation": "Lufthansa Technik Services India",
    "stakeholder": "Marcel Pastuska",
    "designation": "CEO",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 55,
    "organisation": "Hical Technologies Pvt Ltd",
    "stakeholder": "Sujaya Shashikiran",
    "designation": "Director",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "https://www.linkedin.com/in/sujaya-shashikiran-2a3b7984?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3Bya%2BMG3VKSumPeVfGvBe1MA%3D%3D",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 56,
    "organisation": "GKN Aerospace India",
    "stakeholder": "Sunil Dhake",
    "designation": "Managing Director",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "https://www.linkedin.com/in/sunil-dhake-34b8639?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3B9Ti7rKFUS6OvyGH21qNEbQ%3D%3D",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 57,
    "organisation": "GE Aerospace",
    "stakeholder": "Vikram Rai",
    "designation": "CEO, South Asia",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 58,
    "organisation": "Ananth Technologies",
    "stakeholder": "",
    "designation": "",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 59,
    "organisation": "Skyserve",
    "stakeholder": "Vinay S.",
    "designation": "",
    "email": "vinay@skyserve.ai",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "Aditya",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 60,
    "organisation": "Digantara",
    "stakeholder": "Anirudh Sharma",
    "designation": "",
    "email": "anirudh.sharma@digantara.co.in",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "Aditya",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 61,
    "organisation": "Pixxel Space",
    "stakeholder": "Awais Ahmed",
    "designation": "",
    "email": "Awais@pixxel.space",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "Aditya",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 62,
    "organisation": "Dhruva Space",
    "stakeholder": "Sanjay Nekkanti",
    "designation": "",
    "email": "sanjay@dhruvaspace.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "Aditya",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 63,
    "organisation": "Agnikul",
    "stakeholder": "Srinath Ravichandran",
    "designation": "",
    "email": "srinath@agnikul.in",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "Aditya",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 64,
    "organisation": "Skyroot",
    "stakeholder": "Bharath Daka",
    "designation": "",
    "email": "bharath@skyroot.co.in",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "Aditya",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 65,
    "organisation": "Bellatrix",
    "stakeholder": "Yashas Karanam",
    "designation": "",
    "email": "yashas@bellatrix.aero",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "Aditya",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 66,
    "organisation": "Azista Industries",
    "stakeholder": "Sunil Indurti",
    "designation": "",
    "email": "sunil@azistaindustries.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "Aditya",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 67,
    "organisation": "Bharat Forge",
    "stakeholder": "Amit Kalyani",
    "designation": "",
    "email": "abkalyani@bharatforge.com",
    "phone": "Bhakti Sharma, PR & Corp Comm (70309 42840)",
    "location": "",
    "industry": "",
    "mainBusiness": "Component Manufacturing",
    "linkedin": "",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 68,
    "organisation": "Society of Indian Defence Manufacturers (SIDM)",
    "stakeholder": "Rajinder Singh Bhatia (also Chairman, Kalyani Strategic Systems Limited)",
    "designation": "President",
    "email": "rajinderbhatia@bharatforge.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "Industry Body",
    "linkedin": "",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 69,
    "organisation": "Kalyani Strategic Systems Limited (part of Bharat Forge)",
    "stakeholder": "Neelesh Tungar",
    "designation": "CEO",
    "email": "neelesh.tungar@bharatforge.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "Component Manufacturing",
    "linkedin": "",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 70,
    "organisation": "Sweden-India Business Council",
    "stakeholder": "Cecilia Oldne",
    "designation": "Chief India Representative",
    "email": "cecilia.oldne@sibc.se",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "Industry Body",
    "linkedin": "",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 71,
    "organisation": "PwC India",
    "stakeholder": "Captain Vishal Kanwar (Retd)",
    "designation": "Partner, Aerospace & Defence",
    "email": "vishal.kanwar@pwc.com, himanshu.suryavanshi@pwc.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "Consulting Practice",
    "linkedin": "",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 72,
    "organisation": "Ernst & Young",
    "stakeholder": "Pawan Khatter",
    "designation": "Partner and National Aerospace & Defence Leader",
    "email": "pawan.khatter@in.ey.com, kuber.kandadai@in.ey.com",
    "phone": "9899455604, 9871143381",
    "location": "",
    "industry": "",
    "mainBusiness": "Consulting Practice",
    "linkedin": "",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 73,
    "organisation": "Bharat Dynamics Ltd",
    "stakeholder": "Cmde Girish Raghunath Pradhan (Retd.), Ajay Bansal (Head, International Sales)",
    "designation": "Executive Director (BD)",
    "email": "bdbdl@bdl-india.in",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "Component Manufacturing",
    "linkedin": "",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 74,
    "organisation": "Ashok Leyland",
    "stakeholder": "Amandeep Singh, Rajesh Mani",
    "designation": "Head (Defence Business); Head (Marketing & Corporate Communications)",
    "email": "amandeep.singh@ashokleyland.com, Rajesh.Mani@ashokleyland.com",
    "phone": "Rajesh Mani (9500022922)",
    "location": "",
    "industry": "",
    "mainBusiness": "Component Manufacturing",
    "linkedin": "",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 75,
    "organisation": "Adani Defence & Aerospace",
    "stakeholder": "Ashish Rajvanshi",
    "designation": "CEO",
    "email": "ashish.rajvanshi@adani.com, sukriti.jain@adani.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "Component Manufacturing",
    "linkedin": "",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 76,
    "organisation": "Mazagon Dock Shipbuilders Ltd",
    "stakeholder": "Capt Jagmohan (Retd.)",
    "designation": "Chairman & MD",
    "email": "chmd@mazdock.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "Component Manufacturing",
    "linkedin": "",
    "pointOfContact": "Carl",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 77,
    "organisation": "Aequs",
    "stakeholder": "Aravind Melligeri, Rajeev Kaul",
    "designation": "",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 78,
    "organisation": "Magellan Aerospace",
    "stakeholder": "",
    "designation": "",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 79,
    "organisation": "TATA Advanced Systems Ltd",
    "stakeholder": "Sukaran Singh",
    "designation": "CEO",
    "email": "ssingh@tata.com, skchokshi@tataadvancedsystems.com",
    "phone": "9223301710 (Sarika Kapoor Chokshi)",
    "location": "Send email & proposal",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 80,
    "organisation": "Mahindra Group",
    "stakeholder": "S.P. Shukla",
    "designation": "President, Defence",
    "email": "shukla.sp@mahindra.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 81,
    "organisation": "VEM Technologies Pvt. Ltd",
    "stakeholder": "V. Venkata Raju",
    "designation": "Chairman & MD",
    "email": "vvr@vemtechnologies.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 82,
    "organisation": "Airbus",
    "stakeholder": "Anand Stanley",
    "designation": "President, Asia Pacific",
    "email": "anand.stanley@airbus.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 83,
    "organisation": "Bombardier",
    "stakeholder": "Sudhir Rao",
    "designation": "CEO & MD",
    "email": "sudhir.rao@in.transport.bombardier",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 84,
    "organisation": "Lockheed Martin",
    "stakeholder": "Michael Fernandez",
    "designation": "Country Head - India",
    "email": "michael.fernandez@lmco.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 85,
    "organisation": "Google",
    "stakeholder": "Mansi Khanna",
    "designation": "Director, Ads and Brand & Reputation Marketing",
    "email": "mansikhanna@google.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 86,
    "organisation": "Microsoft",
    "stakeholder": "Garima Rathore",
    "designation": "Director, Government Affairs and Public Policy",
    "email": "grathore@microsoft.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 87,
    "organisation": "Meta",
    "stakeholder": "Aman Jain",
    "designation": "Senior Director & Country Head, Public Policy",
    "email": "",
    "phone": "Already written to Sunil Abraham",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 88,
    "organisation": "Amazon",
    "stakeholder": "Chetan Krishnaswamy, Prasanna Karthik",
    "designation": "VP, Public Policy",
    "email": "ck@amazon.com, prasnkar@amazon.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 89,
    "organisation": "Apple",
    "stakeholder": "Naveen Tandon",
    "designation": "Head - Policy & Strategy",
    "email": "naveen_tandon@apple.com",
    "phone": "98111 63896",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 90,
    "organisation": "3M India Ltd",
    "stakeholder": "Ramesh Ramadurai",
    "designation": "Managing Director",
    "email": "rramesh1@mmm.com, inayera@mmm.com",
    "phone": "8022231414",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 91,
    "organisation": "Accenture India",
    "stakeholder": "Puneet Kumar",
    "designation": "Director, Public Policy & Government Affairs",
    "email": "puneet.j.kumar@accenture.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 92,
    "organisation": "AMD",
    "stakeholder": "Arvind Chandrasekar",
    "designation": "Senior Director, Govt Affairs",
    "email": "arvind.chandrasekar@amd.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 93,
    "organisation": "Ametek",
    "stakeholder": "Sadanand Patil",
    "designation": "Managing Director",
    "email": "sadanand.patil@ametek.com",
    "phone": "98459 79211",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 94,
    "organisation": "Amway",
    "stakeholder": "Rajneesh Chopra",
    "designation": "CEO",
    "email": "rajneesh.chopra@amway.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 95,
    "organisation": "Analog Devices",
    "stakeholder": "Srinivas Prasad R",
    "designation": "Director & India Site Head",
    "email": "srinivas.prasad@analog.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 96,
    "organisation": "Wesco Anixter",
    "stakeholder": "S Sunil Pai",
    "designation": "Country Manager",
    "email": "sunil.pai@anixter.com",
    "phone": "98455 61555",
    "location": "Resend email",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 97,
    "organisation": "Applied Materials",
    "stakeholder": "Ashwini K. Aggarwal",
    "designation": "Former Director, Govt Affairs (currently teaching at Manav Rachna)",
    "email": "",
    "phone": "99105 55970",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 98,
    "organisation": "Aptiv Components India",
    "stakeholder": "Amitabh Mathur",
    "designation": "President & MD",
    "email": "amitabh.mathur@aptiv.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 99,
    "organisation": "Arcesium",
    "stakeholder": "Ranvijay Lamba",
    "designation": "Managing Director & Country Head",
    "email": "ranvijay.lamba@arcesium.com",
    "phone": "0404639 0000",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 100,
    "organisation": "Ares Operations India",
    "stakeholder": "Sandesh Hegde",
    "designation": "Chief Operations Officer",
    "email": "shegde@aresmgmt.com",
    "phone": "98922 25797",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 101,
    "organisation": "Ashland India Pvt Ltd",
    "stakeholder": "Nelson Corda",
    "designation": "General Manager",
    "email": "ncorda@ashland.com",
    "phone": "022 6282 8730",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 102,
    "organisation": "AT&T",
    "stakeholder": "Amit Kushwaha",
    "designation": "Director, External and Regulatory Affairs",
    "email": "amit.kushwaha@intl.att.com",
    "phone": "99588 03555",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 103,
    "organisation": "Avery Dennison",
    "stakeholder": "Saurabh Agarwal",
    "designation": "Vice President & General Manager",
    "email": "saurabh.agarwal@ap.averydennison.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 104,
    "organisation": "Baker Hughes",
    "stakeholder": "Neeraj Sethi",
    "designation": "Country Director \u2013 India & Bangaldesh",
    "email": "neeraj.sethi@bakerhughes.com",
    "phone": "72890 51661",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 105,
    "organisation": "Bank of America",
    "stakeholder": "K. Ganesh",
    "designation": "Director",
    "email": "k.ganesh@bofa.com",
    "phone": "80 - 6600 6224",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 106,
    "organisation": "Suntory Global Spirits",
    "stakeholder": "Neeraj Kumar",
    "designation": "Managing Director",
    "email": "neeraj.kumar@beamsuntory.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 107,
    "organisation": "Becton Dickinson India",
    "stakeholder": "Atul Grover",
    "designation": "Managing Director",
    "email": "atul.grover@bd.com",
    "phone": "93233 52717",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 108,
    "organisation": "Belcan India Pvt Ltd",
    "stakeholder": "Naveen Munnangi",
    "designation": "Director",
    "email": "nmunnangi@belcan.in",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 109,
    "organisation": "Boeing India Pvt Ltd",
    "stakeholder": "Salil Anil Gupte",
    "designation": "President, Boeing India & South Asia",
    "email": "salil.gupte@boeing.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 110,
    "organisation": "BorgWarner Morse Systems",
    "stakeholder": "R. Murali",
    "designation": "Director",
    "email": "rmurali@borgwarner.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 111,
    "organisation": "Boston Scientific",
    "stakeholder": "Manoj Madhavan",
    "designation": "Managing Director",
    "email": "manoj.madhavan@bsci.com",
    "phone": "96673 78840",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 112,
    "organisation": "Broadridge India",
    "stakeholder": "Sheenam Ohrie",
    "designation": "Managing Director",
    "email": "sheenam.ohrie@broadridge.com",
    "phone": "98450 52882",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 113,
    "organisation": "C.H. Robinson",
    "stakeholder": "Madhav Thapar",
    "designation": "Vice President",
    "email": "madhav.thapar@chrobinson.com",
    "phone": "88790 90294",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 114,
    "organisation": "Cadence Design Systems",
    "stakeholder": "Jaswinder Ahuja",
    "designation": "Corporate Vice President",
    "email": "jassi_ahuja@yahoo.com",
    "phone": "98111 15150",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 115,
    "organisation": "Carrier",
    "stakeholder": "Arun Bhatia",
    "designation": "Managing Director",
    "email": "arun.bhatia@carrier.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 116,
    "organisation": "Caterpillar India Pvt Ltd",
    "stakeholder": "Ruby Thapar",
    "designation": "Director, Global Govt. & Corporate Affairs",
    "email": "",
    "phone": "CSR Strategist",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 117,
    "organisation": "Caterpillar India Pvt Ltd",
    "stakeholder": "Vivekanand Vanmeeganathan",
    "designation": "Director",
    "email": "Vanmeeganathan_vivekanand@cat.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 118,
    "organisation": "CBRE",
    "stakeholder": "Anshuman Magazine",
    "designation": "Chairman & CEO",
    "email": "anshuman.magazine@cbre.co.in",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 119,
    "organisation": "CDK Global India Pvt Ltd",
    "stakeholder": "Arvind Ramsewak Chaturvedi",
    "designation": "Managing Director",
    "email": "arvind.chaturvedi@cdk.com",
    "phone": "99630 77411",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 120,
    "organisation": "Cisco Systems India",
    "stakeholder": "Harish Krishnan",
    "designation": "Managing Director & Chief Policy Officer - India & SAARC",
    "email": "harkris2@cisco.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 121,
    "organisation": "Citi Bank India",
    "stakeholder": "Nelson Chaudhuri",
    "designation": "Head, Government Affairs",
    "email": "nelson.chaudhuri@citi.com",
    "phone": "90518 10668,  99991 40894",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 122,
    "organisation": "The Coca Cola Company",
    "stakeholder": "Devyani R L Rana",
    "designation": "Vice President \u2013 Public Affairs, Communications and Sustainability",
    "email": "drlranasingh@gmail.com",
    "phone": "98102 75651",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 123,
    "organisation": "Cognizant",
    "stakeholder": "K. Purushothaman",
    "designation": "Head - Government Affairs (States)",
    "email": "purushothaman.k@cognizant.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 124,
    "organisation": "Colgate Palmolive",
    "stakeholder": "Prabha Narasimhan",
    "designation": "Managing Director",
    "email": "prabha_narasimhan@colpal.com, consumeraffairs_india@colpal.com",
    "phone": "99621 54540, 95821 44443",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 125,
    "organisation": "Congruent Info-Tech",
    "stakeholder": "Asish Datta",
    "designation": "COO & CFO",
    "email": "asish@congruentindia.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 126,
    "organisation": "MacDermid Alpha Electronics Solutions ",
    "stakeholder": "Dr. Ravi M. Bhatkal",
    "designation": "VP, Strategy",
    "email": "ravi.bhatkal@macdermid.com, ravi.bhatkal@macdermidalpha.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 127,
    "organisation": "Corning Technologies India Pvt Ltd",
    "stakeholder": "Sunanda Sehgal",
    "designation": "Regional HR Head",
    "email": "sehgals@corning.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 128,
    "organisation": "Crane India",
    "stakeholder": "Hari Jinaga",
    "designation": "President & MD",
    "email": "hjinaga@cranecpe.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 129,
    "organisation": "Cushman & Wakefield",
    "stakeholder": "Somy Thomas",
    "designation": "Executive MD, Land & Capital Markets",
    "email": "somy.thomas@ap.cushwake.com",
    "phone": "80 - 4046 5555",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 130,
    "organisation": "D. E. Shaw India Private Limited",
    "stakeholder": "Charitra Mehta",
    "designation": "Managing Director",
    "email": "charitra.mehta@deshaw.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 131,
    "organisation": "International Flavors & Fragrances (IFF)",
    "stakeholder": "Prakash MG",
    "designation": "Senior VP",
    "email": "prakash.mg@iff.com",
    "phone": "99308 20087",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 132,
    "organisation": "Dastur Energy",
    "stakeholder": "Atanu Mukherjee",
    "designation": "CEO",
    "email": "atanu.m@dasturenergy.com, atanu.m@dastur.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 133,
    "organisation": "DCG Data Core Systems",
    "stakeholder": "Pinaki Ranjan Ghosh",
    "designation": "COO",
    "email": "pinaki.ghosh@datacoresystems.com",
    "phone": "98308 08893",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 134,
    "organisation": "Deloitte Consulting India",
    "stakeholder": "Hemant Kumar",
    "designation": "MD, Global Services",
    "email": "hemkumar@deloitte.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 135,
    "organisation": "Dell",
    "stakeholder": "Manish Gupta",
    "designation": "MD",
    "email": "manish.k.gupta@dell.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 136,
    "organisation": "Dover India",
    "stakeholder": "Tushar Banerjee",
    "designation": "MD",
    "email": "",
    "phone": "80 - 4112 3421",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 137,
    "organisation": "Dow Jones",
    "stakeholder": "Pallavi Malviya",
    "designation": "Regional Director, South Asia",
    "email": "",
    "phone": "90043 09378",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 138,
    "organisation": "Dun & Bradstreet",
    "stakeholder": "Avinash Gupta",
    "designation": "Managing Director & CEO",
    "email": "avinash.gupta@dnb.com",
    "phone": "98199 32367",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 139,
    "organisation": "Duracell India",
    "stakeholder": "Chetan Deshmukh",
    "designation": "Director",
    "email": "deshmukh.c@duracell.com",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 140,
    "organisation": "Eastman Chemical India",
    "stakeholder": "Vishaw Bhushan Sud",
    "designation": "Regional Commercial Manager",
    "email": "vbsud@eastman.com",
    "phone": "98101 82966",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 141,
    "organisation": "Anthropic India",
    "stakeholder": "Irina Ghosh",
    "designation": "Managing Director",
    "email": "ighose@anthropic.com",
    "phone": "8042184521, 98861 18008",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 142,
    "organisation": "Google Gemini",
    "stakeholder": "Preeti Lobana, Anuj Gulati",
    "designation": "VP & Country Manager, Head of Global Growth Marketing (Google Gemini)",
    "email": "lobanpr@google.com, plobana@google.com, anujgulati@google.com",
    "phone": "9810755119",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 143,
    "organisation": "Vedanta (As a platinum sponsor)",
    "stakeholder": "Anil Agarwal, Dhiraj Nayyar",
    "designation": "Non-Executive Chairman",
    "email": "",
    "phone": "",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  },
  {
    "id": 144,
    "organisation": "Kirloskar Defence Systems",
    "stakeholder": "George Verghese, Rahul Sahai",
    "designation": "Managing Director, CEO (Kirloskar Oil Engines Ltd)",
    "email": "rahul.sahai@kirloskar.com",
    "phone": "70422 02851, 90398 68359",
    "location": "",
    "industry": "",
    "mainBusiness": "",
    "linkedin": "",
    "pointOfContact": "",
    "stage": "New Lead",
    "programme": "BGD",
    "meetingDate": "",
    "notes": ""
  }
];
